# Generated by Django 5.2.16 on 2026-07-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplier_name',
        ),
    ]
