# Generated by Django 5.2.16 on 2026-07-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_brand_product_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_name',
            new_name='supplier',
        ),
    ]
